### ISSUE TITLE
Arduino IDE Integration Debian/Linux

### ISSUE THREAD

**Issue by fhasex20** [geolink/opentracker-arduino-board#1]
I've tried to add the URL to the Arduino IDE, but it complains about "Bossac"

if you're Looking at the JSON-File, the problem seems to be that there is no "host" defined for Linux, as it is for the other dependencies. Should the version shipped with Debian work? Or is it possible to provide a working binary for linux?
{
          "name": "bossac",
          "version": "1.4-opentracker",
          "systems": [
            {
              "host": "i686-mingw32",
              "url": "https://github.com/geolink/opentracker-bossa/releases/download/1.4-opentracker/bossac-1.4-opentracker-i686-mingw32.tar.bz2",
              "archiveFileName": "bossac-1.4-opentracker-i686-mingw32.tar.bz2",
              "checksum": "SHA-256:c197ab61cd073e2a41e9ffc608482998616fc0d8db1978e6c2e491858c8bce40",
              "size": "213711"
            }

**Comment by ppescher** [comment]
Yes, you are right. There is no linux binary yet.

I don't have access to a linux machine now (and for a couple weeks), so maybe you can try to fork https://github.com/geolink/opentracker-bossa and build it yourself (make sure you use the opentracker branch).

**Comment by ppescher** [comment]
Just added Linux binaries to opentracker-bossa and updated the package JSON (now version 1.0.1)
Please try it out and report back, thanks!

**Comment by fhasex20** [comment]
Hello Paolo,
I can confirm that the Binary is working on Debian 64bits (jessie)

Ferdinand Haselbacher
